### ISSUE TITLE
Pressing sin/cos/tan and then another operation causes garbled display 

### ISSUE THREAD

**Issue by rahlskog** [abhx-x11/pycalctk#1]
If I do one of the sin/tan/cos operations and then do another operation not in that set it causes the new answer to be overlaid on top of the old.

![image](https://user-images.githubusercontent.com/3809563/150544916-c1babef1-4372-43cd-9c50-8ae99bd91433.png)

Windows 10
Python 3.8.2

**Comment by abhx-x11** [comment]
Wait have you clicked the clear button? The main source code is for linux because i wrote the main code on a linux machine and i opened it on a windows machine but dont worry in the main repo i should fix the bug in a few days

**Comment by rahlskog** [comment]
Yes the clear button somewhat works around it. Was more unexpected behavior that sin/tan/cos overwrites previous answer but then the +-*/ doesnt overwrite those but do overwrite themselves.

Also the clear for me leaves first and last digit visible

**Comment by abhx-x11** [comment]
Well @rahlskog  your issue has been patched and the autoclear function works `properly.
I request you to open more issues and the patch will be available soon :)
